spring.application.name=main-cars-service

server.port=8080

# database config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tcars
spring.datasource.username=postgres
spring.datasource.password=007953hh

# connection pool config
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=50

# uploading images restriction
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# rabbit connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# spring cloud stream for rabbitmq (define binder between exchanger and queue)
spring.cloud.stream.defaultBinder=rabbit

# output channels for rabbit messages (queue will be named as destination.consumerGroup)
spring.cloud.stream.bindings.outputChannel.destination=toStorageCarImageQueue
spring.cloud.stream.bindings.outputChannel.content-type=application/json

spring.cloud.stream.bindings.avatarOutputChannel.destination=toStorageAvatarImageQueue
spring.cloud.stream.bindings.avatarOutputChannel.content-type=application/json

##input channel to receive images from storage service
#spring.cloud.stream.bindings.inputChannel.destination=fromStorageCarImageQueue
## define consumer group which will listen our inputChannel destination
#spring.cloud.stream.bindings.inputChannel.group=carImageResponse
#spring.cloud.stream.bindings.inputChannel.content-type=application/json