spring.application.name=main-cars-service

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tcars
spring.datasource.username=postgres
spring.datasource.password=007953hh

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=50
